#!/usr/bin/env python3
"""
Generate a local .env file for docker-compose from machine credentials.

Reads:
  ~/.aws/credentials  [ecs] section — Dell ECS S3 keys for IMPACT slides
  ~/.databrickscfg    [DEFAULT]     — Databricks PAT

Usage:
  python3 tools/write_dev_env.py > .env
  docker compose up --build
"""
import configparser
import os
import sys


def _section(cfg: configparser.ConfigParser, section: str) -> configparser.SectionProxy | dict:
    if cfg.has_section(section):
        return cfg[section]
    if section.upper() == "DEFAULT":
        return cfg.defaults()
    return {}


def main() -> None:
    aws = configparser.ConfigParser()
    aws.read(os.path.expanduser("~/.aws/credentials"))

    dbc = configparser.ConfigParser()
    dbc.read(os.path.expanduser("~/.databrickscfg"))

    ecs = aws["ecs"] if aws.has_section("ecs") else {}

    dbc_def = dict(dbc.defaults())

    host = dbc_def.get("host", "")
    token = dbc_def.get("token", "")
    if not host or not token:
        print("WARNING: ~/.databrickscfg DEFAULT profile missing host or token",
              file=sys.stderr)

    if not ecs.get("aws_access_key_id"):
        print("WARNING: no [ecs] section found in ~/.aws/credentials",
              file=sys.stderr)

    lines = [
        "# Auto-generated by tools/write_dev_env.py — do NOT commit",
        "",
        "# ── Dell ECS (MSK IMPACT slides) — canonical AWS SDK env var names ──",
        f"AWS_ENDPOINT_URL={ecs.get('endpoint_url', 'http://pmindecs.mskcc.org:9020')}",
        f"AWS_ACCESS_KEY_ID={ecs.get('aws_access_key_id', '')}",
        f"AWS_SECRET_ACCESS_KEY={ecs.get('aws_secret_access_key', '')}",
        "",
        "# ── Databricks ────────────────────────────────────────────────────",
        f"DATABRICKS_HOST={host}",
        f"DATABRICKS_TOKEN={token}",
        "DATABRICKS_WAREHOUSE_ID=0b49b7d78734ad5c",
        "",
        "# ── Local dev overrides ───────────────────────────────────────────",
        "PATIENT_CACHE_TTL=60",
        "MAX_OPEN_SLIDES=8",
        "REDIS_MAXMEMORY=256mb",
        "APP_MEMORY_LIMIT=4g",
        "CORS_ORIGINS=http://localhost:8080,http://localhost:3000",
        "SERVER_PORT=8080",
        "ANNOTATION_DB_PATH=/data/annotations.db",
        "# Optional: point annotations at Lakebase/Postgres instead of local SQLite.",
        "# ANNOTATION_DATABASE_URL=postgresql://<user>:<password>@<host>:5432/<database>?sslmode=require",
        "",
        "# ── OncoKB ────────────────────────────────────────────────────────",
        "# Register at https://www.oncokb.org/account/settings to obtain a token.",
        "ONCOKB_API_TOKEN=",
    ]
    print("\n".join(lines))


if __name__ == "__main__":
    main()
